version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
  codecov: codecov/codecov@5.3.0
jobs:
  verify-back-end:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Verify
          command: mvn -B -f ./back-end/pom.xml clean verify
      - codecov/upload

  verify-front-end:
    working_directory: ~/e-commerce-full-stack
    docker:
      - image: cimg/node:18.20.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "front-end/package-lock.json" }}
      - run: npm --prefix front-end install --force
      - save_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "front-end/package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm --prefix front-end run build

workflows:
  e-commetce-full-stack-build:
    jobs:
      - verify-back-end
      - verify-front-end
