version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build-and-test-back-end:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -f ./back-end/pom.xml -DskipTests clean package
      - run:
          name: Test
          command: mvn -f ./back-end/pom.xml test

  build-and-test-front-end:
    working_directory: ~/e-commerce-full-stack
    docker:
      - image: cimg/node:18.20.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "front-end/package-lock.json" }}
      - run: npm --prefix front-end install
      - save_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "front-end/package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm --prefix front-end run build

workflows:
  e-commetce-full-stack-build:
    jobs:
      - build-and-test-back-end
      - build-and-test-front-end
