server:
  port: 8008
  error:
    include-message: always
    include-binding-errors: always
  shutdown: graceful

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-ecommerce
    username: postgres
    password: postgres
    hikari:
      pool-name: "db-pool"
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    redis:
      use-key-prefix: true
      key-prefix: "cache_"
      enable-statistics: true
      time-to-live: 5m

  liquibase:
    change-log: classpath:liquibase/changelog-master.xml

# swagger / springdoc
springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs

# actuator
management:
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# logging
logging:
  level:
    ua:
      mike: trace
    net:
      ttddyy:
        dsproxy:
          listener: debug

logbook:
  format:
    style: splunk
  predicate:
    exclude:
      - path: /actuator**
      - path: ${springdoc.api-docs.path}**
      - path: ${springdoc.swagger-ui.path}**