server:
  port: 8008
  error:
    include-message: always
    include-binding-errors: always
  shutdown: graceful

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-ecommerce
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      #debug hibernate queries
      hibernate.show_sql: false
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:liquibase/changelog-master.xml

# swagger / springdoc
springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs

# actuator
management:
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# logging
logging:
  level:
    ua.mike: trace

logbook:
  format:
    style: splunk
  predicate:
    exclude:
      - path: /actuator**