server:
  port: 8008

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/full-stack-ecommerce
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      #debug hibernate queries
      hibernate.show_sql: false
      hibernate.use_sql_comments: true
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.xml

# swagger / springdoc
springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs

# logging
logging:
  level:
    ua.mike: trace